
#ifndef GENERATED_RTC_TIME_H
#define GENERATED_RTC_TIME_H

#define INIT_RTC_HOURS    0x18
#define INIT_RTC_MINUTES  0x35
#define INIT_RTC_SECONDS  0x1
#define INIT_RTC_WEEKDAY  RTC_WEEKDAY_FRIDAY
#define INIT_RTC_MONTH    RTC_MONTH_JULY
#define INIT_RTC_DATE     0x19
#define INIT_RTC_YEAR     0x24

#endif // GENERATED_RTC_TIME_H
