
#ifndef GENERATED_RTC_TIME_H
#define GENERATED_RTC_TIME_H

#define INIT_RTC_HOURS    0x20
#define INIT_RTC_MINUTES  0x9
#define INIT_RTC_SECONDS  0x42
#define INIT_RTC_WEEKDAY  RTC_WEEKDAY_MONDAY
#define INIT_RTC_MONTH    RTC_MONTH_APRIL
#define INIT_RTC_DATE     0x6
#define INIT_RTC_YEAR     0x26

#endif // GENERATED_RTC_TIME_H
